@puerto = http://localhost:8001
@doctorId = aedc89bf-4e52-42ed-981d-8a16802400c7


### CREATE - Crear un nuevo doctor
POST {{puerto}}/doctores
Content-Type: application/json

{
    "nombre": "Dr. Jose Ruben",
    "especialidad": "xxx"
}

###

### READ - Obtener todos los doctores
GET {{puerto}}/doctores

###

### READ - Obtener un doctor por ID
GET {{puerto}}/doctores/{{doctorId}}

###

### UPDATE - Actualizar un doctor
PUT {{puerto}}/doctores/{{doctorId}}
Content-Type: application/json

{
    "nombre": "Dr. Jose Ruben Clemente",
    "especialidad": "patologia"
}

###

### DELETE - Eliminar un doctor
DELETE {{puerto}}/doctores/{{doctorId}}

###
